---
- name: Ensure KeyBindings directory exists
  file:
    path: "{{ ansible_env.HOME }}/Library/KeyBindings"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: '0755'
    
- name: Configure Home, End, and additional key bindings for macOS
  copy:
    dest: "{{ ansible_env.HOME }}/Library/KeyBindings/DefaultKeyBinding.dict"
    content: |
      {
      "\UF729" = "moveToBeginningOfLine:";                            /* Home */
      "\UF72B" = "moveToEndOfLine:";                                  /* End */
      "$\UF729" = "moveToBeginningOfLineAndModifySelection:";         /* Shift + Home */
      "$\UF72B" = "moveToEndOfLineAndModifySelection:";               /* Shift + End */
      "@\UF729" = "moveToBeginningOfDocument:";                       /* Cmd + Home */
      "@\UF72B" = "moveToEndOfDocument:";                             /* Cmd + End */
      "@$\UF729" = "moveToBeginningOfDocumentAndModifySelection:";    /* Shift + Cmd + Home */
      "@$\UF72B" = "moveToEndOfDocumentAndModifySelection:";          /* Shift + Cmd + End */
      "@\Uf702" = "moveWordLeft:";                                    /* Cmd + Left */
      "@\Uf703" = "moveWordRight:";                                   /* Cmd + Right */
      "@$\Uf702" = "moveWordLeftAndModifySelection:";                 /* Shift + Cmd + Left */
      "@$\Uf703" = "moveWordRightAndModifySelection:";                /* Shift + Cmd + Right */
      }
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: '0644'
    force: yes
    # killall Finder &&  # killall Dock && killall SystemUIServer