---
- name: Update user-specific settings in .gitconfig
  blockinfile:
    path: "{{ ansible_env.HOME }}/.gitconfig"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - user section"
    block: |
      [user]
          name = {{ git_username }}
          email = {{ git_email }}
    state: present
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: '0644'