---
- name: Write user-specific gitconfig
  copy:
    dest: "{{ ansible_env.HOME }}/.gitconfig-user"
    content: |
      [user]
        name = {{ git_username }}
        email = {{ git_email }}
    owner: "{{ ansible_user_id }}"
    group: staff
    mode: '0644'